site_name: "Premières NSI - Lycée Ste Marie"
site_url: https://davidjannel.github.io/premieres_NSI_smb/
repo_url: https://github.com/davidJannel/premieres_NSI_smb
edit_uri: tree/main/docs/
site_description: Cours premières spécialité NSI
docs_dir: docs

theme:
    name: material
    custom_dir: my_theme_customizations/
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    favicon: xtra/logo.png
    logo: xtra/logo.png
    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue grey
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: Mode sombre

        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue grey
          accent: indigo
          toggle:
            icon: material/toggle-switch
            name: Mode clair
    features:
        - navigation.instant
        - navigation.tabs
        # - navigation.tabs.sticky
        # - navigation.sections
        - navigation.expand
        # - navigation.tracking
        - navigation.top
        - toc.integrate
        - header.autohide

markdown_extensions:
    - meta
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences:          # Imbrication de blocs.
        preserve_tabs: true
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 3


plugins:
  - search
  - macros
  # - enumerate-headings

extra_javascript:
  - xtra/javascripts/mathjax-config.js                    # MathJax
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - xtra/javascripts/interpreter.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-maths.js
# - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
# - javascripts/mermaid.js

extra_css:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/css/massilia-maths.css
  - stylesheets/extra.css
  - xtra/stylesheets/pyoditeur.css
  - xtra/stylesheets/qcm.css
  - xtra/stylesheets/ajustements.css                      # ajustements

copyright: CC BY-SA / D. Jannel
